services:
    nextjs:
        build:
            dockerfile: docker/dev.Dockerfile
            context: .
        volumes:
            - ./lib:/app/lib:ro,z
            - ./pages:/app/pages:ro,z
            - ./public:/app/public:z
            - ./styles:/app/styles:ro,z
        restart: unless-stopped
        ports:
            - 3000:3000
