services:
    nextjs:
        build:
            dockerfile: docker/prod.Dockerfile
            context: .
        restart: unless-stopped
        ports:
            - 3000:3000
        depends_on:
            - postgres
        environment:
            - DATABASE_URL=postgresql://ordinary-dev:e2t6dm0f@postgres:5432/altweb?schema=public

    postgres:
        image: postgres
        volumes:
            - altweb-postgres-prod:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=ordinary-dev
            - POSTGRES_PASSWORD=e2t6dm0f
            - POSTGRES_DB=altweb
        restart: unless-stopped

volumes:
    altweb-postgres-prod:
